# from enum import Enum


class CONSTANTS:
    googleTrendsAPIMethodURL = 'http://localhost:3000/volatilitypred/extractTrends/'
    yahooFinanceAPIMethodURL = 'http://localhost:3000/volatilitypred/extractFinance/'
    google_trend_map = 'gtrendsdata'

    EXTENSION_EXCEL = '.xlsx'

    start_date = '2012-01-01'
    # start_date = '2019-12-30'
    end_date = '2019-12-31'

    # Column_names
    trend_ceros = 'trend_ceros'
    trend_unos = 'trend_unos'
    finance_ceros = 'finance_ceros'
    finance_unos = 'finance_unos'
    precision = 'precision'
    recall = 'recall'
    f1 = 'f1'
    sklearn_metrics = 'sklearn.metrics'
    binary = 'binary'
    weighted = 'weighted'
    covarianza_normalizadas = 'covarianza_normalizadas'
    # ----------------------------------------

    index_results_path = 'result_data/all_index/'
    ibex_results_path = 'result_data/ibex/'
    nasdaq_results_path = 'result_data/nasdaq/'
    sp500_results_path = 'result_data/sp500/'
    dax30_results_path = 'result_data/dax30/'
    dummy_results_path = 'result_data/dummy/'

    LIBRARY = ''
    RESULTS_PATH = ''

    DUMMY_STOCK_LIBRARY = {
      'MTX': 'MTU Aero Engines',
      'ADS': 'Adidas',
      'ALV': 'Allianz',
      'MMM': '3M Company',
      'AMZN': 'Amazon',  # 'Amazon.com Inc.'
      'BBVA.MC': 'BBVA',
    }

    ALL_INDEX_LIBRARY = {
      '^IBEX': 'IBEX',
      '^GDAXI': 'DAX',
      '^GSPC': 'S&P 500'
    }

    IBEX_STOCK_LIBRARY = {
      'ANA.MC': 'Acciona S.A.',
      'ACX.MC': 'Acerinox',  # 'Acerinox S.A.',
      'ACS.MC': 'ACS Actividades de Construccion y Servicios',
      'AENA.MC': 'Aena',  # 'Aena S.M.E.',
      'AMS.MC': 'Amadeus IT Group',
      'MTS.MC': 'ArcelorMittal',
      'BBVA.MC': 'BBVA',
      'SAB.MC': 'Sabadell',
      'SAN.MC': 'Banco Santander',
      'BKT.MC': 'Bankinter',
      'CABK.MC': 'CaixaBank',
      'CLNX.MC': 'Cellnex',  # 'Cellnex Telecom',
      'ENG.MC': 'Enagas',  # 'Enagas, S.A.',
      'ENC.MC': 'ENCE',  # 'ENCE Energia y Celulosa, S.A.',
      'ELE.MC': 'Endesa',  # 'Endesa, Sociedad Anonima',
      'FER.MC': 'Ferrovial S.A.',  # 'Ferrovial, S.A.',
      'GRF.MC': 'Grifols',  # 'Grifols, S.A.',
      'IBE.MC': 'Iberdrola',  # 'Iberdrola, S.A.',
      'ITX.MC': 'ITX.MC',  # 'Industria de Diseno Textil, S.A.',
      'COL.MC': 'Inmobiliaria Colonial',  # 'Inmobiliaria Colonial, SOCIMI, S.A.',
      'IAG.MC': 'International Consolidated Airlines',  # 'International Consolidated Airlines Group, S.A.',
      'MAP.MC': 'Mapfre',  # 'Mapfre, S.A.',
      'TL5.MC': 'Mediaset España',  # 'Mediaset Espana Comunicacion, S.A.',
      'MEL.MC': 'Melia Hotels',  # 'Melia Hotels International, S.A.',
      'MRL.MC': 'MERLIN Properties',  # 'MERLIN Properties SOCIMI, S.A.',
      'NTGY.MC': 'Naturgy Energy',  # 'Naturgy Energy Group, S.A.',
      'REE.MC': 'Red Electrica Corporacion',  # 'Red Electrica Corporacion, S.A.',
      'SGRE.MC': 'Siemens Gamesa',  # 'Siemens Gamesa Renewable Energy, S.A.',
      'TEF.MC': 'Telefónica',  # 'Telefónica, S.A.',
      'VIS.MC': 'Viscofan'  # 'Viscofan, S.A.'
    }

    DAX30_STOCK_LIBRARY = {
      'ADS': 'Adidas',
      'ALV': 'Allianz',
      'BAS': 'BASF',
      'BAY': 'Bayer',
      'BEI': 'Beiersdorf',
      'BMW': 'BMW',
      'CON': 'Continental',
      '1COV': 'Covestro',
      'DAI': 'Daimler',
      'DBK': 'Deutsche Bank',
      'DB1': 'Deutsche Börse',
      'LHA': 'Deutsche Lufthansa',
      'DPW': 'Deutsche Post',
      'DTE': 'Deutsche Telekom',
      'EOA': 'E.ON',
      'FRE3': 'Fresenius',
      'FME': 'Fresenius Medical Care',
      'HEI': 'HeidelbergCement',
      'HEN3': 'Henkel',
      'IFX': 'Infineon',
      'LIN': 'Linde',
      'MRK': 'Merck',
      'MTX': 'MTU Aero Engines',
      'MUV2': 'Münchener Rück',
      'RWE': 'RWE',
      'SAP': 'SAP',
      'SIE': 'Siemens',
      'VOW': 'Volkswagen Group',
      'VNA': 'Vonovia',
      'WDI': 'Wirecard'
    }

    SP500_STOCK_LIBRARY_1 = {
      'MMM': '3M Company',
      'ABT': 'Abbott Laboratories',
      'ABBV': 'AbbVie Inc.',
      'ABMD': 'ABIOMED Inc',
      'ACN': 'Accenture plc',
      'ATVI': 'Activision Blizzard',
      'ADBE': 'Adobe Inc.',
      'AMD': 'Advanced Micro Devices Inc',
      'AAP': 'Advance Auto Parts',
      'AES': 'AES Corp',
      'AFL': 'AFLAC Inc',
      'A': 'Agilent Technologies Inc',
      'APD': 'Air Products & Chemicals Inc',
      'AKAM': 'Akamai Technologies Inc',
      'ALK': 'Alaska Air',  # 'Alaska Air Group Inc',
      'ALB': 'Albemarle Corp',
      'ARE': 'Alexandria Real Estate Equities',
      'ALXN': 'Alexion Pharmaceuticals',
      'ALGN': 'Align Technology',
      'ALLE': 'Allegion',
      'LNT': 'Alliant',  # 'Alliant Energy Corp',
      'ALL': 'Allstate',  # 'Allstate Corp',
      'GOOGL': 'Google'  # 'Alphabet Inc. (Class A)',
    }

    SP500_STOCK_LIBRARY_2 = {
      'GOOG': 'Google',  # 'Alphabet Inc. (Class C)',
      'MO': 'Altria',  # 'Altria Group Inc',
      'AMZN': 'Amazon',  # 'Amazon.com Inc.',
      'AMCR': 'Amcor',  # 'Amcor plc',
      'AEE': 'Ameren',  # 'Ameren Corp',
      'AAL': 'American Airlines',  # 'American Airlines Group',
      'AEP': 'American Electric Power',
      'AXP': 'American Express',  # 'American Express Co',
      'AIG': 'American International Group',
      'AMT': 'American Tower',  # 'American Tower Corp.',
      'AWK': 'American Water Works Company',  # 'American Water Works Company Inc',
      'AMP': 'Ameriprise Financial',
      'ABC': 'AmerisourceBergen',  # 'AmerisourceBergen Corp',
      'AME': 'AMETEK',  # 'AMETEK Inc.',
      'AMGN': 'Amgen',  # 'Amgen Inc.',
      'APH': 'Amphenol',  # 'Amphenol Corp',
      'ADI': 'Analog Devices, Inc.',
      'ANSS': 'ANSYS',
      'ANTM': 'Anthem',
      'AON': 'Aon',  # 'Aon plc',
      'AOS': 'A.O. Smith'  # 'A.O. Smith Corp',

    }

    SP500_STOCK_LIBRARY_3 = {
      'APA': 'Apache Corporation',
      'AIV': 'Apartment Investment & Management',
      'AAPL': 'Apple Inc.',
      'AMAT': 'Applied Materials Inc.',
      'APTV': 'Aptiv PLC',
      'ADM': 'Archer-Daniels-Midland Co',
      'ANET': 'Arista Networks',
      'AJG': 'Arthur J. Gallagher & Co.',
      'AIZ': 'Assurant',
      'T': 'AT&T',  # 'AT&T Inc.',
      'ATO': 'Atmos Energy',
      'ADSK': 'Autodesk Inc.',
      'ADP': 'Automatic Data Processing',
      'AZO': 'AutoZone Inc',
      'AVB': 'AvalonBay Communities',
      'AVY': 'Avery Dennison',  # 'Avery Dennison Corp',
      'BKR': 'Baker Hughes',  # 'Baker Hughes Co',
      'BLL': 'Ball Corp',
      'BAC': 'Bank of America',  # 'Bank of America Corp',
      'BK': 'Bank of New York Mellon',  # 'The Bank of New York Mellon',
      'BAX': 'Baxter International',  # 'Baxter International Inc.',
      'BDX': 'Becton Dickinson',
      'BRK.B': 'Berkshire Hathaway',
      'BBY': 'Best Buy',  # 'Best Buy Co. Inc.',
      'BIO': 'Bio-Rad Laboratories',
      'BIIB': 'Biogen Inc.',
      'BLK': 'BlackRock',
      'BA': 'Boeing',  # 'Boeing Company',
      'BKNG': 'Booking Holdings',  # 'Booking Holdings Inc',
    }

    SP500_STOCK_LIBRARY_4 = {
      'BWA': 'BorgWarner',
      'BXP': 'Boston Properties',
      'BSX': 'Boston Scientific',
      'BMY': 'Bristol-Myers Squibb',
      'AVGO': 'Broadcom Inc.',
      'BR': 'Broadridge Financial Solutions',
      'BF.B': 'Brown-Forman',  # 'Brown-Forman Corp.',
      'CHRW': 'C. H. Robinson Worldwide',
      'COG': 'Cabot Oil & Gas',
      'CDNS': 'Cadence Design Systems',
      'CPB': 'Campbell Soup',
      'COF': 'Capital One Financial',
      'CAH': 'Cardinal Health',  # 'Cardinal Health Inc.',
      'KMX': 'Carmax',  # 'Carmax Inc',
      'CCL': 'Carnival Corp.',
      'CARR': 'Carrier Global',
      'CAT': 'Caterpillar',  # 'Caterpillar Inc.',
      'CBOE': 'Cboe',  # 'Cboe Global Markets',
      'CBRE': 'CBRE Group',
      'CDW': 'CDW',
      'CE': 'Celanese',
      'CNC': 'Centene Corporation',
      'CNP': 'CenterPoint Energy',
      'CTL': 'CenturyLink',  # 'CenturyLink Inc',
      'CERN': 'Cerner',
      'CF': 'CF Industries Holdings',  # 'CF Industries Holdings Inc',
      'SCHW': 'Charles Schwab Corporation',
      'CHTR': 'Charter Communications',
      'CVX': 'Chevron',  # 'Chevron Corp.',
      'CMG': 'Chipotle Mexican Grill',
      'CB': 'Chubb Limited',
      'CHD': 'Church & Dwight'
    }

    SP500_STOCK_LIBRARY_5 = {
      'CI': 'CIGNA',  # 'CIGNA Corp.',
      'CINF': 'Cincinnati Financial',
      'CTAS': 'Cintas Corporation',
      'CSCO': 'Cisco',  # 'Cisco Systems',
      'C': 'Citigroup',  # 'Citigroup Inc.',
      'CFG': 'Citizens Financial',  # 'Citizens Financial Group',
      'CTXS': 'Citrix Systems',
      'CLX': 'The Clorox Company',
      'CME': 'CME Group',  # 'CME Group Inc.',
      'CMS': 'CMS Energy',
      'KO': 'Coca-Cola',  # 'Coca-Cola Company',
      'CTSH': 'Cognizant Technology Solutions',
      'CL': 'Colgate-Palmolive',
      'CMCSA': 'Comcast Corp.',
      'CMA': 'Comerica',  # 'Comerica Inc.',
      'CAG': 'Conagra Brands',
      'CXO': 'Concho Resources',
      'COP': 'ConocoPhillips',
      'ED': 'Consolidated Edison',
      'STZ': 'Constellation Brands',
      'COO': 'The Cooper Companies',
      'CPRT': 'Copart',  # 'Copart Inc',
      'GLW': 'Corning',  # 'Corning Inc.',
      'CTVA': 'Corteva',
      'COST': 'Costco',  # 'Costco Wholesale Corp.',
      'COTY': 'Coty',  # 'Coty, Inc',
      'CCI': 'Crown Castle International',  # 'Crown Castle International Corp.',
      'CSX': 'CSX',  # 'CSX Corp.',
      'CMI': 'Cummins',  # 'Cummins Inc.',
      'CVS': 'CVS Health',
      'DHI': 'D. R. Horton'

    }

    SP500_STOCK_LIBRARY_6 = {
      'DHR': 'Danaher',  # 'Danaher Corp.',
      'DRI': 'Darden Restaurants',
      'DVA': 'DaVita',  # 'DaVita Inc.',
      'DE': 'Deere & Co.',
      'DAL': 'Delta Air Lines',  # 'Delta Air Lines Inc.',
      'XRAY': 'Dentsply Sirona',
      'DVN': 'Devon Energy',
      'DXCM': 'DexCom',
      'FANG': 'Diamondback Energy',
      'DLR': 'Digital Realty Trust Inc',
      'DFS': 'Discover Financial Services',
      'DISCA': 'Discovery',  # 'Discovery, Inc. (Class A)',
      'DISCK': 'Discovery',  # 'Discovery, Inc. (Class C)',
      'DISH': 'Dish Network',
      'DG': 'Dollar General',
      'DLTR': 'Dollar Tree',
      'D': 'Dominion Energy',
      'DPZ': "Domino's Pizza",
      'DOV': 'Dover Corporation',
      'DOW': 'Dow',  # 'Dow Inc.',
      'DTE': 'DTE Energy Co.',  # 'DTE Energy',
      'DUK': 'Duke Energy',
      'DRE': 'Duke Realty',  # 'Duke Realty Corp',
      'DD': 'DuPont de Nemours',  # 'DuPont de Nemours Inc',
      'DXC': 'DXC',  # 'DXC Technology',
      'ETFC': 'E*Trade',
      'EMN': 'Eastman Chemical',
      'ETN': 'Eaton Corporation',
      'EBAY': 'eBay',  # 'eBay Inc.',
      'ECL': 'Ecolab',  # 'Ecolab Inc.',
      'EIX': "Edison Int'l"
    }

    SP500_STOCK_LIBRARY_7 = {
      'EW': 'Edwards Lifesciences',
      'EA': 'Electronic Arts',
      'EMR': 'Emerson Electric',  # 'Emerson Electric Company',
      'ETR': 'Entergy',  # 'Entergy Corp.',
      'EOG': 'EOG Resources',
      'EFX': 'Equifax',  # 'Equifax Inc.',
      'EQIX': 'Equinix',
      'EQR': 'Equity Residential',
      'ESS': 'Essex Property Trust',  # 'Essex Property Trust, Inc.',
      'EL': 'Estée Lauder',  # 'Estée Lauder Companies',
      'EVRG': 'Evergy',
      'ES': 'Eversource Energy',
      'RE': 'Everest Re Group',  # 'Everest Re Group Ltd.',
      'EXC': 'Exelon',  # 'Exelon Corp.',
      'EXPE': 'Expedia',  # 'Expedia Group',
      'EXPD': 'Expeditors',
      'EXR': 'Extra Space Storage',
      'XOM': 'Exxon Mobil',  # 'Exxon Mobil Corp.',
      'FFIV': 'F5 Networks',
      'FB': 'Facebook',  # 'Facebook, Inc.',
      'FAST': 'Fastenal',  # 'Fastenal Co',
      'FRT': 'Federal Realty Investment Trust',
      'FDX': 'FedEx',  # 'FedEx Corporation',
      'FIS': 'Fidelity National Information Services',
      'FITB': 'Fifth Third Bancorp',
      'FE': 'FirstEnergy Corp',
      'FRC': 'First Republic Bank',
      'FISV': 'Fiserv',  # 'Fiserv Inc',
      'FLT': 'FleetCor Technologies',  # 'FleetCor Technologies Inc',
      'FLIR': 'FLIR Systems',
      'FLS': 'Flowserve Corporation',
      'FMC': 'FMC Corporation',
      'F': 'Ford Motor',  # 'Ford Motor Company',
      'FTNT': 'Fortinet',
      'FTV': 'Fortive',  # 'Fortive Corp',
      'FBHS': 'Fortune Brands Home & Security',
      'FOXA': 'Fox',  # 'Fox Corporation (Class A)',
      'FOX': 'Fox',  # 'Fox Corporation (Class B)',
      'BEN': 'Franklin Resources',
      'FCX': 'Freeport-McMoRan',  # 'Freeport-McMoRan Inc.',
      'GPS': 'Gap'  # 'Gap Inc.',
    }

    SP500_STOCK_LIBRARY_8 = {
      'GRMN': 'Garmin',  # 'Garmin Ltd.',
      'IT': 'Gartner',  # 'Gartner Inc',
      'GD': 'General Dynamics',
      'GE': 'General Electric',
      'GIS': 'General Mills',
      'GM': 'General Motors',
      'GPC': 'Genuine Parts',
      'GILD': 'Gilead Sciences',
      'GL': 'Globe Life',  # 'Globe Life Inc.',
      'GPN': 'Global Payments',  # 'Global Payments Inc.',
      'GS': 'Goldman Sachs',  # 'Goldman Sachs Group',
      'GWW': 'Grainger',  # 'Grainger (W.W.) Inc.',
      'HRB': 'H&R Block',
      'HAL': 'Halliburton',  # 'Halliburton Co.',
      'HBI': 'Hanesbrands',  # 'Hanesbrands Inc',
      'HIG': 'Hartford Financial',  # 'Hartford Financial Svc.Gp.',
      'HAS': 'Hasbro',  # 'Hasbro Inc.',
      'HCA': 'HCA Healthcare',
      'PEAK': 'Healthpeak Properties',
      'HSIC': 'Henry Schein',
      'HSY': 'The Hershey Company',
      'HES': 'Hess Corporation',
      'HPE': 'Hewlett Packard',  # 'Hewlett Packard Enterprise',
      'HLT': 'Hilton Worldwide Holdings',  # 'Hilton Worldwide Holdings Inc',
      'HFC': 'HollyFrontier',  # 'HollyFrontier Corp',
      'HOLX': 'Hologic',
      'HD': 'Home Depot',
      'HON': "Honeywell Int'l",  # "Honeywell Int'l Inc.",
      'HRL': 'Hormel Foods Corp.',
      'HST': 'Host Hotels & Resorts',
      'HWM': 'Howmet Aerospace',
      'HPQ': 'HPQ',  # 'HP Inc.',
      'HUM': 'Humana',  # 'Humana Inc.',
      'HBAN': 'Huntington Bancshares',
      'HII': 'Huntington Ingalls',  # 'Huntington Ingalls Industries',
      'IEX': 'IDEX Corporation',
      'IDXX': 'IDEXX Laboratories',
      'INFO': 'IHS Markit',  # 'IHS Markit Ltd.',
      'ITW': 'Illinois Tool Works',
      'ILMN': 'Illumina'  # 'Illumina Inc'
    }

    SP500_STOCK_LIBRARY_9 = {
      'INCY': 'Incyte',
      'IR': 'Ingersoll Rand',
      'INTC': 'Intel',  # 'Intel Corp.',
      'ICE': 'Intercontinental Exchange',
      'IBM': 'IBM',  # 'International Business Machines',
      'IP': 'International Paper',
      'IPG': 'Interpublic Group',
      'IFF': 'International Flavors & Fragrances',
      'INTU': 'Intuit',  # 'Intuit Inc.',
      'ISRG': 'Intuitive Surgical',  # 'Intuitive Surgical Inc.',
      'IVZ': 'Invesco',  # 'Invesco Ltd.',
      'IPGP': 'IPG Photonics',  # 'IPG Photonics Corp.',
      'IQV': 'IQVIA Holdings',  # 'IQVIA Holdings Inc.',
      'IRM': 'Iron Mountain',  # 'Iron Mountain Incorporated',
      'JKHY': 'Jack Henry & Associates',
      'J': 'Jacobs Engineering Group',
      'JBHT': 'J. B. Hunt Transport Services',
      'SJM': 'JM Smucker',
      'JNJ': 'Johnson & Johnson',
      'JCI': 'Johnson Controls International',
      'JPM': 'JPMorgan',  # 'JPMorgan Chase & Co.',
      'JNPR': 'Juniper',  # 'Juniper Networks',
      'KSU': 'Kansas City Southern',
      'K': 'Kellogg',  # 'Kellogg Co.',
      'KEY': 'KeyCorp',
      'KEYS': 'Keysight Technologies',
      'KMB': 'Kimberly-Clark',
      'KIM': 'Kimco Realty',
      'KMI': 'Kinder Morgan',
      'KLAC': 'KLAC',  # 'KLA Corporation',
      'KSS': "Kohl's",  # "Kohl's Corp.",
      'KHC': 'Kraft Heinz',  # 'Kraft Heinz Co',
    }

    SP500_STOCK_LIBRARY_10 = {
      'KR': 'Kroger',  # 'Kroger Co.',
      'LB': 'L Brands',  # 'L Brands Inc.',
      'LHX': 'L3Harris',  # 'L3Harris Technologies',
      'LH': 'Laboratory of America Holding',  # 'Laboratory Corp. of America Holding',
      'LRCX': 'Lam Research',
      'LW': 'Lamb Weston Holdings',  # 'Lamb Weston Holdings Inc',
      'LVS': 'Vegas Sands',  # 'Las Vegas Sands',
      'LEG': 'Leggett & Platt',
      'LDOS': 'Leidos Holdings',
      'LEN': 'Lennar',  # 'Lennar Corp.',
      'LLY': 'Lilly (Eli) & Co.',
      'LNC': 'Lincoln National',
      'LIN': 'Linde plc',
      'LYV': 'Live Nation Entertainment',
      'LKQ': 'LKQ',  # 'LKQ Corporation',
      'LMT': 'Lockheed Martin',  # 'Lockheed Martin Corp.',
      'L': 'Loews ',  # 'Loews Corp.',
      'LOW': "Lowe's",  # "Lowe's Cos.",
      'LYB': 'LyondellBasell',
      'MTB': 'M&T Bank',  # 'M&T Bank Corp.',
      'MRO': 'Marathon Oil',  # 'Marathon Oil Corp.',
      'MPC': 'Marathon Petroleum',
      'MKTX': 'MarketAxess',
      'MAR': "Marriott",  # "Marriott Int'l.",
      'MMC': 'Marsh & McLennan',
      'MLM': 'Martin Marietta Materials',
      'MAS': 'Masco',  # 'Masco Corp.',
      'MA': 'Mastercard',  # 'Mastercard Inc.',
      'MKC': 'McCormick',  # 'McCormick & Co.',
      'MXIM': 'Maxim Integrated',  # 'Maxim Integrated Products Inc',
      'MCD': "McDonald's",  # "McDonald's Corp.",
      'MCK': 'McKesson',  # 'McKesson Corp.',
      'MDT': 'Medtronic'  # 'Medtronic plc',
    }

    SP500_STOCK_LIBRARY_11 = {
      'MRK': 'Merck & Co.',
      'MET': 'MetLife',  # 'MetLife Inc.',
      'MTD': 'Mettler Toledo',
      'MGM': 'MGM Resorts International',
      'MCHP': 'Microchip Technology',
      'MU': 'Micron Technology',
      'MSFT': 'Microsoft',  # 'Microsoft Corp.',
      'MAA': 'Mid-America Apartments',
      'MHK': 'Mohawk Industries',
      'TAP': 'Molson Coors Beverage',  # 'Molson Coors Beverage Company',
      'MDLZ': 'Mondelez',  # 'Mondelez International',
      'MNST': 'Monster Beverage',
      'MCO': "Moody's",  # "Moody's Corp",
      'MS': 'Morgan Stanley',
      'MOS': 'The Mosaic Company',
      'MSI': 'Motorola',  # 'Motorola Solutions Inc.',
      'MSCI': 'MSCI',  # 'MSCI Inc',
      'MYL': 'Mylan N.V.',
      'NDAQ': 'Nasdaq',  # 'Nasdaq, Inc.',
      'NOV': 'National Oilwell Varco',  # 'National Oilwell Varco Inc.',
      'NTAP': 'NetApp',
      'NFLX': 'Netflix',  # 'Netflix Inc.',
      'NWL': 'Newell Brands',
      'NEM': 'Newmont Corporation',
      'NWSA': 'NWSA',  # 'News Corp. Class A',
      'NWS': 'NWS',  # 'News Corp. Class B',
      'NEE': 'NextEra Energy',
      'NLSN': 'Nielsen Holdings',
      'NKE': 'Nike',  # 'Nike, Inc.',
      'NI': 'NiSource',  # 'NiSource Inc.',
      'NBL': 'Noble Energy',  # 'Noble Energy Inc',
      'NSC': 'Norfolk Southern',  # 'Norfolk Southern Corp.',
      'NTRS': 'Northern Trust',  # 'Northern Trust Corp.',
      'NOC': 'Northrop Grumman',
      'NLOK': 'NortonLifeLock'
    }

    SP500_STOCK_LIBRARY_12 = {
      'NCLH': 'Norwegian Cruise Line Holdings',
      'NRG': 'NRG Energy',
      'NUE': 'Nucor',  # 'Nucor Corp.',
      'NVDA': 'Nvidia',  # 'Nvidia Corporation',
      'NVR': 'NVR',  # 'NVR, Inc.',
      'ORLY': "O'Reilly Automotive",
      'OXY': 'Occidental Petroleum',
      'ODFL': 'Old Dominion Freight Line',
      'OMC': 'Omnicom Group',
      'OKE': 'ONEOK',
      'ORCL': 'Oracle',  # 'Oracle Corp.',
      'OTIS': 'Otis Worldwide',
      'PCAR': 'PACCAR',  # 'PACCAR Inc.',
      'PKG': 'Packaging Corporation of America',
      'PH': 'Parker-Hannifin',
      'PAYX': 'Paychex',  # 'Paychex Inc.',
      'PAYC': 'Paycom',
      'PYPL': 'PayPal',
      'PNR': 'Pentair',  # 'Pentair plc',
      'PBCT': "People's United Financial",
      'PEP': 'Pepsi',  # 'PepsiCo Inc.',
      'PKI': 'PerkinElmer',
      'PRGO': 'Perrigo',
      'PFE': 'Pfizer',  # 'Pfizer Inc.',
      'PM': 'Philip Morris International',
      'PSX': 'Phillips 66',
      'PNW': 'Pinnacle West Capital',
      'PXD': 'Pioneer Natural Resources',
      'PNC': 'PNC Financial Services'
    }

    SP500_STOCK_LIBRARY_13 = {
      'CRM': 'Salesforce.com',
      'SBAC': 'SBA Communications',
      'SLB': 'Schlumberger',  # 'Schlumberger Ltd.',
      'STX': 'Seagate Technology',
      'SEE': 'Sealed Air',
      'SRE': 'Sempra Energy',
      'NOW': 'ServiceNow',
      'SHW': 'Sherwin-Williams',
      'SPG': 'Simon Property',  # 'Simon Property Group Inc',
      'SWKS': 'Skyworks Solutions',
      'SLG': 'SL Green Realty',
      'SNA': 'Snap-on',
      'SO': 'Southern Company',
      'LUV': 'Southwest Airlines',
      'SWK': 'Black & Decker',  # 'Stanley Black & Decker',
      'SBUX': 'Starbucks',  # 'Starbucks Corp.',
      'STT': 'State Street Corp.',
      'STE': 'STERIS',  # 'STERIS plc',
      'SYK': 'Stryker Corp.',
      'SIVB': 'SVB Financial',
      'SYF': 'Synchrony Financial',
      'SNPS': 'Synopsys Inc.',
      'SYY': 'Sysco',  # 'Sysco Corp.',
      'TMUS': 'T-Mobile',  # 'T-Mobile US',
      'TROW': 'T. Rowe Price Group',
      'TTWO': 'Take-Two Interactive',
      'TPR': 'Tapestry',  # 'Tapestry, Inc.',
      'TGT': 'Target Corp.',
      'TEL': 'TE Connectivity',  # 'TE Connectivity Ltd.',
      'FTI': 'TechnipFMC',
      'TDY': 'Teledyne Technologies',
      'TFX': 'Teleflex',
      'TXN': 'Texas Instruments',
      'TXT': 'Textron',  # 'Textron Inc.',
      'TMO': 'Thermo Fisher Scientific'
    }

    SP500_STOCK_LIBRARY_14 = {
      'TIF': 'Tiffany & Co.',
      'TJX': 'TJX',  # 'TJX Companies Inc.',
      'TSCO': 'Tractor Supply Company',
      'TT': 'Trane Technologies',  # 'Trane Technologies plc',
      'TDG': 'TransDigm Group',
      'TRV': 'The Travelers Companies',  # 'The Travelers Companies Inc.',
      'TFC': 'Truist Financial',
      'TWTR': 'Twitter',  # 'Twitter, Inc.',
      'TYL': 'Tyler Technologies',
      'TSN': 'Tyson Foods',
      'UDR': 'UDR',  # 'UDR, Inc.',
      'ULTA': 'Ulta Beauty',
      'USB': 'U.S. Bancorp',
      'UAA': 'UAA',  # 'Under Armour (Class A)',
      'UA': 'UA',  # 'Under Armour (Class C)',
      'UNP': 'Union Pacific',  # 'Union Pacific Corp',
      'UAL': 'United Airlines',  # 'United Airlines Holdings',
      'UNH': 'United Health',  # 'United Health Group Inc.',
      'UPS': 'United Parcel Service',
      'URI': 'United Rentals',  # 'United Rentals, Inc.',
      'UHS': 'Universal Health Services',
      'UNM': 'Unum Group',
      'VFC': 'VF Corporation',
      'VLO': 'Valero Energy',
      'VAR': 'Varian Medical Systems',
      'VTR': 'VTR',  # 'Ventas Inc',
      'VRSN': 'Verisign',  # 'Verisign Inc.',
      'VRSK': 'Verisk Analytics',
      'VZ': 'Verizon',  # 'Verizon Communications',
      'VRTX': 'Vertex Pharmaceuticals',  # 'Vertex Pharmaceuticals Inc',
      'VIAC': 'ViacomCBS',
      'V': 'Visa'  # 'Visa Inc.',
    }

    SP500_STOCK_LIBRARY_15 = {
      'VNO': 'Vornado Realty Trust',
      'VMC': 'Vulcan Materials',
      'WRB': 'W. R. Berkley Corporation',
      'WAB': 'Wabtec Corporation',
      'WMT': 'Walmart',
      'WBA': 'Walgreens Boots Alliance',
      'DIS': 'Walt Disney',  # 'The Walt Disney Company',
      'WM': 'Waste Management',  # 'Waste Management Inc.',
      'WAT': 'Waters Corporation',
      'WEC': 'WEC Energy Group',
      'WFC': 'Wells Fargo',
      'WELL': 'Welltower',  # 'Welltower Inc.',
      'WST': 'West Pharmaceutical Services',
      'WDC': 'Western Digital',
      'WU': 'Western Union',  # 'Western Union Co',
      'WRK': 'WestRock',
      'WY': 'Weyerhaeuser',
      'WHR': 'Whirlpool',  # 'Whirlpool Corp.',
      'WMB': 'Williams Companies',
      'WLTW': 'Willis Towers Watson',
      'WYNN': 'Wynn Resorts',  # 'Wynn Resorts Ltd',
      'XEL': 'Xcel Energy',  # 'Xcel Energy Inc',
      'XRX': 'Xerox',
      'XLNX': 'Xilinx',
      'XYL': 'Xylem',  # 'Xylem Inc.',
      'YUM': 'Yum! Brands',  # 'Yum! Brands Inc',
      'ZBRA': 'Zebra Technologies',
      'ZBH': 'Zimmer Biomet',  # 'Zimmer Biomet Holdings',
      'ZION': 'Zions Bancorp',
      'ZTS': 'Zoetis'
    }

    SP500_STOCK_LIBRARY_16 = {
      'PPG': 'PPG Industries',
      'PPL': 'PPL Corp.',
      'PFG': 'Principal Financial Group',
      'PG': 'Procter & Gamble',
      'PGR': 'Progressive Corp.',
      'PLD': 'Prologis',
      'PRU': 'Prudential Financial',
      'PEG': 'PSEG',  # 'Public Service Enterprise Group (PSEG)',
      'PSA': 'Public Storage',
      'PHM': 'PulteGroup',
      'PVH': 'PVH',  # 'PVH Corp.',
      'QRVO': 'Qorvo',
      'PWR': 'Quanta Services',  # 'Quanta Services Inc.',
      'QCOM': 'QUALCOMM',  # 'QUALCOMM Inc.',
      'DGX': 'Quest Diagnostics',
      'RL': 'Ralph Lauren',  # 'Ralph Lauren Corporation',
      'RJF': 'Raymond James Financial',  # 'Raymond James Financial Inc.',
      'RTX': 'Raytheon Technologies',
      'O': 'Realty Income Corporation',
      'REG': 'Regency Centers Corporation',
      'REGN': 'Regeneron Pharmaceuticals',
      'RF': 'Regions Financial',  # 'Regions Financial Corp.',
      'RSG': 'RSG',  # 'Republic Services Inc',
      'RMD': 'ResMed',
      'RHI': 'Robert Half International',
      'ROK': 'Rockwell Automation',  # 'Rockwell Automation Inc.',
      'ROL': 'Rollins Inc.',
      'ROP': 'Roper Technologies',
      'ROST': 'Ross Stores',
      'RCL': 'Royal Caribbean Group',
      'SPGI': 'S&P Global'  # 'S&P Global, Inc.',
    }
